### ISSUE TITLE
Doesn't work with lastest MassTransit

### ISSUE THREAD

**Issue by thedumbtechguy** [NCodeGroup/MassTransit.Extensions.Hosting#1]
Hi, this is great.

Small kink though. Doesn't work with the newest Masstransit 5.1.4.

**Comment by BladeWise** [comment]
I cloned the repository and updated the packages to the latest version, it seems to work so far.

**Comment by thedumbtechguy** [comment]
I meant the official version.

**Comment by polewskm** [comment]
Should be resolved by #2

**Comment by polewskm** [comment]
Verified that new build is compatible with latest version
